version = 1
SPDX-PackageName = "grendel"
SPDX-PackageDownloadLocation = "https://github.com/ubccr/grendel"

[[annotations]]
path = [
    "go.mod",
    "go.sum",
    ".gitmodules",
    "NOTICE",
    "api/openapi-templates/Go/README.mustache",
    "api/openapi.json",
    "configs/grendel.toml.sample",
    "docs/requirements.txt",
    "internal/firmware/Makefile",
    "internal/firmware/boot.ipxe",
    "internal/frontend/.prettierrc",
    "internal/frontend/base.css",
    "internal/frontend/public/loading-states.js",
    "scripts/**",
    "pkg/client/.openapi-generator/VERSION",
    "pkg/client/.openapi-generator-ignore",
    "**.gohtml",
    "**.yaml",
    "**.yml",
    "**.tmpl",
    "**.md",
    "**.sql",
    "**.mustache",
    "**.gitignore",
    "**.go",
]
SPDX-FileCopyrightText = "(C) 2019 Grendel Authors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "docs/pages/images/*",
    "internal/frontend/public/favicon.ico",
]
SPDX-FileCopyrightText = "(C) 2019 Grendel Authors"
SPDX-License-Identifier = "CC-BY-NC-ND-4.0"

[[annotations]]
path = "internal/frontend/public/backgrounds/*"
SPDX-FileCopyrightText = "(C) 2019 Grendel Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "internal/frontend/public/fonts/GeistMonoVariableVF.woff2",
    "internal/frontend/public/fonts/GeistVariableVF.woff2",
]
SPDX-FileCopyrightText = "Copyright (c) 2023 Vercel, in collaboration with basement.studio"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
    "internal/frontend/public/tailwind.css",
    "internal/frontend/tailwind.config.js",
]
SPDX-FileCopyrightText = "Copyright (c) Tailwind Labs, Inc."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "internal/frontend/public/notyf.min.css",
    "internal/frontend/public/notyf.min.js",
]
SPDX-FileCopyrightText = "Copyright (c) 2016-2020 Carlos Roso"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "internal/frontend/public/htmx.min.js",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "0BSD"
